### ISSUE TITLE
"/>" in Top-Left Corner

### ISSUE THREAD

**Issue by parkerrobbins** [pushkin-consortium/pushkin-sitetemplates-default#23]
@conbainbridge 

Google Chrome Version 84.0.4147.89 (Official Build) (64-bit) on Ubuntu 18.04

![image](https://user-images.githubusercontent.com/31826170/88589145-ae4f7900-d026-11ea-82d9-7fbdb0ee0d51.png)

**Comment by conbainbridge** [comment]
Fixed - eliminated redundancy in closing the bootstrap-loading link tag

Relevant commit: https://github.com/pushkin-consortium/pushkin-sitetemplates-default/commit/7935a93cf11a0fc5aee57ac4cc21d0b3d93f3238

**Comment by parkerrobbins** [comment]
I am still getting this.

**pushkin-cli version:** 1.1.4
**Chrome version:** Version 84.0.4147.105 (Official Build) (64-bit)
**OS:** Ubuntu 18.04

![image](https://user-images.githubusercontent.com/31826170/89043577-accbcc80-d316-11ea-85ba-318e6273de5c.png)

**Comment by jkhartshorne** [comment]
I don't think @conbainbridge released a new version of the site template. Try now.

**Comment by conbainbridge** [comment]
Yeah, hadn't learned how yet when I made these updates! Looks good now.

**Comment by parkerrobbins** [comment]
Also looks good for me.
